/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfilingRouteImport } from './routes/profiling'
import { Route as PreprocessingRouteImport } from './routes/preprocessing'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as EclProvisionsRouteImport } from './routes/ecl-provisions'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as DataUploadRouteImport } from './routes/data-upload'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidationIndexRouteImport } from './routes/validation.index'
import { Route as ValidationStressRouteImport } from './routes/validation.stress'
import { Route as ValidationRegulatoryRouteImport } from './routes/validation.regulatory'
import { Route as ValidationPerformanceRouteImport } from './routes/validation.performance'
import { Route as ValidationIntakeRouteImport } from './routes/validation.intake'
import { Route as ValidationFindingsRouteImport } from './routes/validation.findings'
import { Route as ValidationDataQualityRouteImport } from './routes/validation.data-quality'
import { Route as ValidationConceptualRouteImport } from './routes/validation.conceptual'
import { Route as ValidationChallengerRouteImport } from './routes/validation.challenger'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilingRoute = ProfilingRouteImport.update({
  id: '/profiling',
  path: '/profiling',
  getParentRoute: () => rootRouteImport,
} as any)
const PreprocessingRoute = PreprocessingRouteImport.update({
  id: '/preprocessing',
  path: '/preprocessing',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const EclProvisionsRoute = EclProvisionsRouteImport.update({
  id: '/ecl-provisions',
  path: '/ecl-provisions',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const DataUploadRoute = DataUploadRouteImport.update({
  id: '/data-upload',
  path: '/data-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationIndexRoute = ValidationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ValidationRoute,
} as any)
const ValidationStressRoute = ValidationStressRouteImport.update({
  id: '/stress',
  path: '/stress',
  getParentRoute: () => ValidationRoute,
} as any)
const ValidationRegulatoryRoute = ValidationRegulatoryRouteImport.update({
  id: '/regulatory',
  path: '/regulatory',
  getParentRoute: () => ValidationRoute,
} as any)
const ValidationPerformanceRoute = ValidationPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => ValidationRoute,
} as any)
const ValidationIntakeRoute = ValidationIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => ValidationRoute,
} as any)
const ValidationFindingsRoute = ValidationFindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => ValidationRoute,
} as any)
const ValidationDataQualityRoute = ValidationDataQualityRouteImport.update({
  id: '/data-quality',
  path: '/data-quality',
  getParentRoute: () => ValidationRoute,
} as any)
const ValidationConceptualRoute = ValidationConceptualRouteImport.update({
  id: '/conceptual',
  path: '/conceptual',
  getParentRoute: () => ValidationRoute,
} as any)
const ValidationChallengerRoute = ValidationChallengerRouteImport.update({
  id: '/challenger',
  path: '/challenger',
  getParentRoute: () => ValidationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/data-upload': typeof DataUploadRoute
  '/development': typeof DevelopmentRoute
  '/ecl-provisions': typeof EclProvisionsRoute
  '/evaluation': typeof EvaluationRoute
  '/explainability': typeof ExplainabilityRoute
  '/features': typeof FeaturesRoute
  '/models': typeof ModelsRoute
  '/preprocessing': typeof PreprocessingRoute
  '/profiling': typeof ProfilingRoute
  '/settings': typeof SettingsRoute
  '/training': typeof TrainingRoute
  '/validation': typeof ValidationRouteWithChildren
  '/validation/challenger': typeof ValidationChallengerRoute
  '/validation/conceptual': typeof ValidationConceptualRoute
  '/validation/data-quality': typeof ValidationDataQualityRoute
  '/validation/findings': typeof ValidationFindingsRoute
  '/validation/intake': typeof ValidationIntakeRoute
  '/validation/performance': typeof ValidationPerformanceRoute
  '/validation/regulatory': typeof ValidationRegulatoryRoute
  '/validation/stress': typeof ValidationStressRoute
  '/validation/': typeof ValidationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/data-upload': typeof DataUploadRoute
  '/development': typeof DevelopmentRoute
  '/ecl-provisions': typeof EclProvisionsRoute
  '/evaluation': typeof EvaluationRoute
  '/explainability': typeof ExplainabilityRoute
  '/features': typeof FeaturesRoute
  '/models': typeof ModelsRoute
  '/preprocessing': typeof PreprocessingRoute
  '/profiling': typeof ProfilingRoute
  '/settings': typeof SettingsRoute
  '/training': typeof TrainingRoute
  '/validation/challenger': typeof ValidationChallengerRoute
  '/validation/conceptual': typeof ValidationConceptualRoute
  '/validation/data-quality': typeof ValidationDataQualityRoute
  '/validation/findings': typeof ValidationFindingsRoute
  '/validation/intake': typeof ValidationIntakeRoute
  '/validation/performance': typeof ValidationPerformanceRoute
  '/validation/regulatory': typeof ValidationRegulatoryRoute
  '/validation/stress': typeof ValidationStressRoute
  '/validation': typeof ValidationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/data-upload': typeof DataUploadRoute
  '/development': typeof DevelopmentRoute
  '/ecl-provisions': typeof EclProvisionsRoute
  '/evaluation': typeof EvaluationRoute
  '/explainability': typeof ExplainabilityRoute
  '/features': typeof FeaturesRoute
  '/models': typeof ModelsRoute
  '/preprocessing': typeof PreprocessingRoute
  '/profiling': typeof ProfilingRoute
  '/settings': typeof SettingsRoute
  '/training': typeof TrainingRoute
  '/validation': typeof ValidationRouteWithChildren
  '/validation/challenger': typeof ValidationChallengerRoute
  '/validation/conceptual': typeof ValidationConceptualRoute
  '/validation/data-quality': typeof ValidationDataQualityRoute
  '/validation/findings': typeof ValidationFindingsRoute
  '/validation/intake': typeof ValidationIntakeRoute
  '/validation/performance': typeof ValidationPerformanceRoute
  '/validation/regulatory': typeof ValidationRegulatoryRoute
  '/validation/stress': typeof ValidationStressRoute
  '/validation/': typeof ValidationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/data-upload'
    | '/development'
    | '/ecl-provisions'
    | '/evaluation'
    | '/explainability'
    | '/features'
    | '/models'
    | '/preprocessing'
    | '/profiling'
    | '/settings'
    | '/training'
    | '/validation'
    | '/validation/challenger'
    | '/validation/conceptual'
    | '/validation/data-quality'
    | '/validation/findings'
    | '/validation/intake'
    | '/validation/performance'
    | '/validation/regulatory'
    | '/validation/stress'
    | '/validation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/data-upload'
    | '/development'
    | '/ecl-provisions'
    | '/evaluation'
    | '/explainability'
    | '/features'
    | '/models'
    | '/preprocessing'
    | '/profiling'
    | '/settings'
    | '/training'
    | '/validation/challenger'
    | '/validation/conceptual'
    | '/validation/data-quality'
    | '/validation/findings'
    | '/validation/intake'
    | '/validation/performance'
    | '/validation/regulatory'
    | '/validation/stress'
    | '/validation'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/data-upload'
    | '/development'
    | '/ecl-provisions'
    | '/evaluation'
    | '/explainability'
    | '/features'
    | '/models'
    | '/preprocessing'
    | '/profiling'
    | '/settings'
    | '/training'
    | '/validation'
    | '/validation/challenger'
    | '/validation/conceptual'
    | '/validation/data-quality'
    | '/validation/findings'
    | '/validation/intake'
    | '/validation/performance'
    | '/validation/regulatory'
    | '/validation/stress'
    | '/validation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  DataUploadRoute: typeof DataUploadRoute
  DevelopmentRoute: typeof DevelopmentRoute
  EclProvisionsRoute: typeof EclProvisionsRoute
  EvaluationRoute: typeof EvaluationRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  FeaturesRoute: typeof FeaturesRoute
  ModelsRoute: typeof ModelsRoute
  PreprocessingRoute: typeof PreprocessingRoute
  ProfilingRoute: typeof ProfilingRoute
  SettingsRoute: typeof SettingsRoute
  TrainingRoute: typeof TrainingRoute
  ValidationRoute: typeof ValidationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiling': {
      id: '/profiling'
      path: '/profiling'
      fullPath: '/profiling'
      preLoaderRoute: typeof ProfilingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preprocessing': {
      id: '/preprocessing'
      path: '/preprocessing'
      fullPath: '/preprocessing'
      preLoaderRoute: typeof PreprocessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecl-provisions': {
      id: '/ecl-provisions'
      path: '/ecl-provisions'
      fullPath: '/ecl-provisions'
      preLoaderRoute: typeof EclProvisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-upload': {
      id: '/data-upload'
      path: '/data-upload'
      fullPath: '/data-upload'
      preLoaderRoute: typeof DataUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation/': {
      id: '/validation/'
      path: '/'
      fullPath: '/validation/'
      preLoaderRoute: typeof ValidationIndexRouteImport
      parentRoute: typeof ValidationRoute
    }
    '/validation/stress': {
      id: '/validation/stress'
      path: '/stress'
      fullPath: '/validation/stress'
      preLoaderRoute: typeof ValidationStressRouteImport
      parentRoute: typeof ValidationRoute
    }
    '/validation/regulatory': {
      id: '/validation/regulatory'
      path: '/regulatory'
      fullPath: '/validation/regulatory'
      preLoaderRoute: typeof ValidationRegulatoryRouteImport
      parentRoute: typeof ValidationRoute
    }
    '/validation/performance': {
      id: '/validation/performance'
      path: '/performance'
      fullPath: '/validation/performance'
      preLoaderRoute: typeof ValidationPerformanceRouteImport
      parentRoute: typeof ValidationRoute
    }
    '/validation/intake': {
      id: '/validation/intake'
      path: '/intake'
      fullPath: '/validation/intake'
      preLoaderRoute: typeof ValidationIntakeRouteImport
      parentRoute: typeof ValidationRoute
    }
    '/validation/findings': {
      id: '/validation/findings'
      path: '/findings'
      fullPath: '/validation/findings'
      preLoaderRoute: typeof ValidationFindingsRouteImport
      parentRoute: typeof ValidationRoute
    }
    '/validation/data-quality': {
      id: '/validation/data-quality'
      path: '/data-quality'
      fullPath: '/validation/data-quality'
      preLoaderRoute: typeof ValidationDataQualityRouteImport
      parentRoute: typeof ValidationRoute
    }
    '/validation/conceptual': {
      id: '/validation/conceptual'
      path: '/conceptual'
      fullPath: '/validation/conceptual'
      preLoaderRoute: typeof ValidationConceptualRouteImport
      parentRoute: typeof ValidationRoute
    }
    '/validation/challenger': {
      id: '/validation/challenger'
      path: '/challenger'
      fullPath: '/validation/challenger'
      preLoaderRoute: typeof ValidationChallengerRouteImport
      parentRoute: typeof ValidationRoute
    }
  }
}

interface ValidationRouteChildren {
  ValidationChallengerRoute: typeof ValidationChallengerRoute
  ValidationConceptualRoute: typeof ValidationConceptualRoute
  ValidationDataQualityRoute: typeof ValidationDataQualityRoute
  ValidationFindingsRoute: typeof ValidationFindingsRoute
  ValidationIntakeRoute: typeof ValidationIntakeRoute
  ValidationPerformanceRoute: typeof ValidationPerformanceRoute
  ValidationRegulatoryRoute: typeof ValidationRegulatoryRoute
  ValidationStressRoute: typeof ValidationStressRoute
  ValidationIndexRoute: typeof ValidationIndexRoute
}

const ValidationRouteChildren: ValidationRouteChildren = {
  ValidationChallengerRoute: ValidationChallengerRoute,
  ValidationConceptualRoute: ValidationConceptualRoute,
  ValidationDataQualityRoute: ValidationDataQualityRoute,
  ValidationFindingsRoute: ValidationFindingsRoute,
  ValidationIntakeRoute: ValidationIntakeRoute,
  ValidationPerformanceRoute: ValidationPerformanceRoute,
  ValidationRegulatoryRoute: ValidationRegulatoryRoute,
  ValidationStressRoute: ValidationStressRoute,
  ValidationIndexRoute: ValidationIndexRoute,
}

const ValidationRouteWithChildren = ValidationRoute._addFileChildren(
  ValidationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  DataUploadRoute: DataUploadRoute,
  DevelopmentRoute: DevelopmentRoute,
  EclProvisionsRoute: EclProvisionsRoute,
  EvaluationRoute: EvaluationRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  FeaturesRoute: FeaturesRoute,
  ModelsRoute: ModelsRoute,
  PreprocessingRoute: PreprocessingRoute,
  ProfilingRoute: ProfilingRoute,
  SettingsRoute: SettingsRoute,
  TrainingRoute: TrainingRoute,
  ValidationRoute: ValidationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
